ZStack() {
  Group {
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 101, height: 17)
      .offset(x: -857.50, y: -833)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1920, height: 400)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/1920x400"))
      )
      .offset(x: 0, y: -1455.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 172, height: 37)
      .background(.white)
      .cornerRadius(6)
      .offset(x: -468, y: -1370)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1920, height: 1080)
      .background(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: 0, y: -715.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 360, height: 451)
      .background(Color(red: 0.09, green: 0.09, blue: 0.09))
      .cornerRadius(12)
      .offset(x: -378, y: -1010)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 360, height: 456)
      .background(Color(red: 0.09, green: 0.09, blue: 0.09))
      .cornerRadius(12)
      .offset(x: 1, y: -1007.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 360, height: 456)
      .background(Color(red: 0.09, green: 0.09, blue: 0.09))
      .cornerRadius(12)
      .offset(x: 381, y: -1007.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 360, height: 456)
      .background(Color(red: 0.09, green: 0.09, blue: 0.09))
      .cornerRadius(12)
      .offset(x: -378, y: -477.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 360, height: 456)
      .background(Color(red: 0.09, green: 0.09, blue: 0.09))
      .cornerRadius(12)
      .offset(x: 1, y: -477.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 360, height: 456)
      .background(Color(red: 0.09, green: 0.09, blue: 0.09))
      .cornerRadius(12)
      .offset(x: 381, y: -477.50)
  }Group {
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1920, height: 599)
      .background(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: 0, y: 124)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 545, height: 379)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/545x379"))
      )
      .offset(x: 279.50, y: 74)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1, height: 99)
      .background(Color(red: 0.48, green: 0.48, blue: 0.48).opacity(0.21))
      .offset(x: -300.31, y: 563.19)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 278, height: 99)
      .offset(x: -439, y: 563)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1, height: 99)
      .background(Color(red: 0.48, green: 0.48, blue: 0.48).opacity(0.21))
      .offset(x: -12.62, y: 563.19)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 278, height: 99)
      .offset(x: -152, y: 563)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1, height: 99)
      .background(Color(red: 0.48, green: 0.48, blue: 0.48).opacity(0.21))
      .offset(x: 275.06, y: 563.19)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 278, height: 99)
      .offset(x: 136, y: 563)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 277, height: 99)
      .offset(x: 423.50, y: 563)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1920, height: 666)
      .background(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: 0, y: 1035.50)
  }Group {
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 273, height: 273)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/273x273"))
      )
      .offset(x: -431.50, y: 930)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 273, height: 273)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/273x273"))
      )
      .offset(x: -149.50, y: 930)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 273, height: 273)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/273x273"))
      )
      .offset(x: 133.50, y: 930)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 273, height: 273)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/273x273"))
      )
      .offset(x: 415.50, y: 930)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 273, height: 273)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/273x273"))
      )
      .offset(x: -431.50, y: 1223)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 273, height: 273)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/273x273"))
      )
      .offset(x: -149.50, y: 1223)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 273, height: 273)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/273x273"))
      )
      .offset(x: 133.50, y: 1223)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 273, height: 273)
      .background(
        AsyncImage(url: URL(string: "https://via.placeholder.com/273x273"))
      )
      .offset(x: 415.50, y: 1223)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1920, height: 265)
      .background(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: 0, y: 1501)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1, height: 165)
      .background(Color(red: 0.32, green: 0.35, blue: 0.38))
      .offset(x: -82.72, y: 1501.38)
  }Group {
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 495, height: 165)
      .cornerRadius(1)
      .offset(x: -330.50, y: 1501)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 495, height: 165)
      .offset(x: 314.50, y: 1501)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1903, height: 1)
      .background(Color(red: 0.32, green: 0.35, blue: 0.38))
      .offset(x: -8.50, y: 1633.38)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1920, height: 88)
      .background(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: 0, y: 1677.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 90, height: 38)
      .cornerRadius(6)
      .offset(x: -8, y: -832.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 1, height: 24)
      .background(Color(red: 1, green: 1, blue: 1).opacity(0.10))
      .offset(x: -6, y: -832.50)
    Rectangle()
      .foregroundColor(.clear)
      .frame(width: 35, height: 24)
      .offset(x: -23.50, y: -832.50)
    ZStack() {
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 1920, height: 66)
        .background(Color(red: 0.06, green: 0.06, blue: 0.06))
        .offset(x: 0, y: 0)
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 949, height: 66)
        .offset(x: -455.50, y: 0)
      Text("Neutroin")
        .font(Font.custom("Roboto", size: 20))
        .lineSpacing(30)
        .foregroundColor(.white)
        .offset(x: -881, y: 0)
      Text("Services")
        .font(Font.custom("Roboto", size: 17))
        .lineSpacing(20)
        .foregroundColor(.white)
        .offset(x: 556.50, y: -1)
      Text("Portfolio")
        .font(Font.custom("Roboto", size: 17))
        .lineSpacing(20)
        .foregroundColor(.white)
        .offset(x: 663, y: -1)
      Text("About")
        .font(Font.custom("Roboto", size: 17))
        .lineSpacing(20)
        .foregroundColor(.white)
        .offset(x: 758, y: -1)
      Text("Contact")
        .font(Font.custom("Roboto", size: 17))
        .lineSpacing(20)
        .foregroundColor(.white)
        .offset(x: 852.50, y: -1)
    }
    .frame(width: 1920, height: 66)
    .offset(x: 0, y: -1688.50)
    Text("Neutroin - Your One-Stop Shop for Digital Solutions")
      .font(Font.custom("Roboto", size: 64))
      .lineSpacing(70.40)
      .foregroundColor(.white)
      .offset(x: -67.50, y: -1495)
    Text("GET STARTED NOW")
      .font(Font.custom("Roboto", size: 14))
      .lineSpacing(27)
      .foregroundColor(.black)
      .offset(x: -468, y: -1370)
  }Group {
    Text("UI UX Designing")
      .font(Font.custom("Roboto", size: 26))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: -445.50, y: -1203)
    Text("01")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: -523.50, y: -1154)
    Text("We design user-friendly interfaces for web and mobile apps, making sure that your users have a seamless experience with your product. Our designs are created with the latest trends and user behavior patterns in mind.")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -386, y: -1035.50)
    ZStack() {
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 125, height: 36)
        .background(.white)
        .cornerRadius(6)
        .offset(x: 0, y: 0)
      Text("READ MORE")
        .font(Font.custom("Roboto", size: 14))
        .lineSpacing(27)
        .foregroundColor(.black)
        .offset(x: 0, y: -4)
    }
    .frame(width: 125, height: 36)
    .offset(x: -290.50, y: -842.50)
    ZStack() {
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 125, height: 36)
        .background(.white)
        .cornerRadius(6)
        .offset(x: 0, y: 0)
      Text("READ MORE")
        .font(Font.custom("Roboto", size: 14))
        .lineSpacing(27)
        .foregroundColor(.black)
        .offset(x: 0, y: -4)
    }
    .frame(width: 125, height: 36)
    .offset(x: 85.50, y: -842.50)
    ZStack() {
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 125, height: 36)
        .background(.white)
        .cornerRadius(6)
        .offset(x: 0, y: 0)
      Text("READ MORE")
        .font(Font.custom("Roboto", size: 14))
        .lineSpacing(27)
        .foregroundColor(.black)
        .offset(x: 0, y: -4)
    }
    .frame(width: 125, height: 36)
    .offset(x: 464.50, y: -842.50)
    ZStack() {
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 125, height: 36)
        .background(.white)
        .cornerRadius(6)
        .offset(x: 0, y: 0)
      Text("READ MORE")
        .font(Font.custom("Roboto", size: 14))
        .lineSpacing(27)
        .foregroundColor(.black)
        .offset(x: 0, y: -4)
    }
    .frame(width: 125, height: 36)
    .offset(x: 465.50, y: -307.50)
    ZStack() {
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 125, height: 36)
        .background(.white)
        .cornerRadius(6)
        .offset(x: 0, y: 0)
      Text("READ MORE")
        .font(Font.custom("Roboto", size: 14))
        .lineSpacing(27)
        .foregroundColor(.black)
        .offset(x: 0, y: -4)
    }
    .frame(width: 125, height: 36)
    .offset(x: 84.50, y: -307.50)
    ZStack() {
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 125, height: 36)
        .background(.white)
        .cornerRadius(6)
        .offset(x: 0, y: 0)
      Text("READ MORE")
        .font(Font.custom("Roboto", size: 14))
        .lineSpacing(27)
        .foregroundColor(.black)
        .offset(x: 0, y: -4)
    }
    .frame(width: 125, height: 36)
    .offset(x: -295.50, y: -307.50)
    ZStack() {
      Rectangle()
        .foregroundColor(.clear)
        .frame(width: 125, height: 36)
        .background(.white)
        .cornerRadius(6)
        .offset(x: 0, y: 0)
      Text("READ MORE")
        .font(Font.custom("Roboto", size: 14))
        .lineSpacing(27)
        .foregroundColor(.black)
        .offset(x: 0, y: -4)
    }
    .frame(width: 125, height: 36)
    .offset(x: -515.50, y: 264.50)
  }Group {
    Text("Mobile App Development")
      .font(Font.custom("Roboto", size: 26))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: -14, y: -1203)
    Text("02")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: -144.50, y: -1154)
    Text("Our team of experienced developers creates high-quality mobile apps for iOS and Android platforms. We take care of everything from ideation to deployment.")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -5.50, y: -1062.50)
    Text("Web Development")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: 325.50, y: -1203)
    Text("03")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: 235.50, y: -1154)
    Text("We build responsive websites that work seamlessly on all devices. Our team has expertise in front-end and back-end web technologies, ensuring that your website is fast, secure, and scalable.")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: 376.50, y: -1049)
    Text("Brand Designing")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: -443.50, y: -673)
    Text("04")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: -523.50, y: -624)
    Text("We create unique and memorable brand identities that communicate your brand’s values and resonate with your target audience. Our designs are adaptable and scalable, ensuring that they grow with your business.")
      .font(Font.custom("Roboto", size: 18))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -380.50, y: -505.50)
    Text("Product Designing")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: -53, y: -673)
  }Group {
    Text("05")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: -144.50, y: -624)
    Text("We help you create products that are both user-friendly and visually appealing. Our team of designers works closely with you to understand your product’s requirements and deliver a design that meets your needs.")
      .font(Font.custom("Roboto", size: 18))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: 0, y: -505.50)
    Text("E-commerce Development")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: 373, y: -673)
    Text("06")
      .font(Font.custom("Roboto", size: 25))
      .lineSpacing(28.60)
      .foregroundColor(.white)
      .offset(x: 235.50, y: -624)
    Text("We build e-commerce websites that are optimized for conversion and provide a seamless shopping experience for your customers. Our team ensures that your website is secure, fast, and easy to use.")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: 374.50, y: -518)
    Text("Designing and developing digital experiences that drive results.")
      .font(Font.custom("Roboto", size: 40))
      .lineSpacing(52)
      .foregroundColor(.white)
      .offset(x: -320, y: -6.50)
    Text("Welcome to Neutroin, the premier mobile app and web designing and development company. We specialize in crafting end-to-end digital solutions that help businesses thrive in today's fast-paced digital world. Our expert team is dedicated to delivering exceptional results to help you achieve your goals.")
      .font(Font.custom("Roboto", size: 18))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -308, y: 159)
    Text("Facebook")
      .font(Font.custom("Roboto", size: 20))
      .lineSpacing(20)
      .foregroundColor(Color(red: 0.41, green: 0.45, blue: 0.49))
      .offset(x: 31.50, y: -199639.50)
    Text("Twitter")
      .font(Font.custom("Roboto", size: 20))
      .lineSpacing(20)
      .foregroundColor(Color(red: 0.41, green: 0.45, blue: 0.49))
      .offset(x: 78.50, y: -199659.50)
    Text("Youtube")
      .font(Font.custom("Roboto", size: 20))
      .lineSpacing(20)
      .foregroundColor(Color(red: 0.41, green: 0.45, blue: 0.49))
      .offset(x: 122, y: -199649.50)
  }Group {
    Text("Behance")
      .font(Font.custom("Roboto", size: 20))
      .lineSpacing(20)
      .foregroundColor(Color(red: 0.41, green: 0.45, blue: 0.49))
      .offset(x: 167, y: -199649.50)
    Text("Pinterest")
      .font(Font.custom("Roboto", size: 20))
      .lineSpacing(20)
      .foregroundColor(Color(red: 0.41, green: 0.45, blue: 0.49))
      .offset(x: 212, y: -199629.50)
    Text("Instagram")
      .font(Font.custom("Roboto", size: 20))
      .lineSpacing(20)
      .foregroundColor(Color(red: 0.41, green: 0.45, blue: 0.49))
      .offset(x: 260, y: -199659.50)
    Text("150")
      .font(Font.custom("Roboto", size: 40))
      .lineSpacing(52)
      .foregroundColor(Color(red: 0.37, green: 0.60, blue: 0.92))
      .offset(x: -451, y: 549.50)
    Text("+")
      .font(Font.custom("Roboto", size: 40))
      .lineSpacing(52)
      .foregroundColor(Color(red: 0.37, green: 0.60, blue: 0.92))
      .offset(x: -406, y: 549.50)
    Text("Projects completed")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: -440, y: 589)
    Text("130")
      .font(Font.custom("Roboto", size: 40))
      .lineSpacing(52)
      .foregroundColor(Color(red: 0.37, green: 0.60, blue: 0.92))
      .offset(x: -153, y: 549.50)
    Text("Happy clients")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: -152.50, y: 589)
    Text("25")
      .font(Font.custom("Roboto", size: 40))
      .lineSpacing(52)
      .foregroundColor(Color(red: 0.37, green: 0.60, blue: 0.92))
      .offset(x: 123.50, y: 549.50)
    Text("+")
      .font(Font.custom("Roboto", size: 40))
      .lineSpacing(52)
      .foregroundColor(Color(red: 0.37, green: 0.60, blue: 0.92))
      .offset(x: 158, y: 549.50)
  }Group {
    Text("Awards received")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: 135.50, y: 589)
    Text("40")
      .font(Font.custom("Roboto", size: 40))
      .lineSpacing(52)
      .foregroundColor(Color(red: 0.37, green: 0.60, blue: 0.92))
      .offset(x: 422.50, y: 549.50)
    Text("Team members")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(Color(red: 0.13, green: 0.13, blue: 0.13))
      .offset(x: 423, y: 589)
    Text("Our clients")
      .font(Font.custom("Roboto", size: 23))
      .lineSpacing(31.20)
      .foregroundColor(.white)
      .offset(x: -9, y: 758.50)
    Text("FOLLOW US")
      .font(Font.custom("Roboto", size: 24))
      .lineSpacing(24)
      .foregroundColor(.white)
      .offset(x: -513.50, y: 1427.50)
    Text("Instagram")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -537.50, y: 1476)
    Text("Behance")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -292.50, y: 1476)
    Text("Facebook")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -540, y: 1523)
    Text("YouTube")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -291.50, y: 1523)
    Text("Dribbble")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -546, y: 1570)
  }Group {
    Text("Twitter")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -299, y: 1570)
    Text("CONTACT")
      .font(Font.custom("Roboto", size: 24))
      .lineSpacing(24)
      .foregroundColor(.white)
      .offset(x: 129, y: 1427.50)
    Text("Mumbai, INDIA.")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: 137.50, y: 1486)
    Text("+91 9892526032")
      .font(Font.custom("Roboto", size: 14))
      .lineSpacing(30)
      .foregroundColor(.white)
      .offset(x: 133, y: 1521.50)
    Text("neutroin@gmail.com")
      .font(Font.custom("Roboto", size: 14))
      .lineSpacing(30)
      .foregroundColor(.white)
      .offset(x: 145.50, y: 1553.50)
    Text("Neutroin Digital Agency")
      .font(Font.custom("Roboto", size: 17))
      .lineSpacing(27)
      .foregroundColor(.white)
      .offset(x: -8, y: 1677)
  }
}
.frame(width: 1920, height: 3443)
.background(.white)